apiVersion: apps/v1
kind: Deployment
metadata:
  name: siparis-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: siparis-api
  template:
    metadata:
      labels:
        app: siparis-api
    spec:
      containers:
      - name: siparis-api
        image: siparis-api:v1
        imagePullPolicy: Never
        env:
        - name: DB_CONNECTION_STRING
          value: "Host=postgres-service;Database=SiparisDb;Username=postgres;Password=YOUR_SECURE_PASSWORD"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: siparis-api-service
spec:
  type: NodePort
  selector:
    app: siparis-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
